"""protocols table: add col is cool

Revision ID: 0974ecc7059c
Revises: a5d44f24dd74
Create Date: 2019-05-12 01:17:23.068006

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0974ecc7059c'
down_revision = 'a5d44f24dd74'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('protocols', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_cool', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('protocols', schema=None) as batch_op:
        batch_op.drop_column('is_cool')

    # ### end Alembic commands ###
